Button buttonStart;
Button buttonA;
Button buttonB;
Button buttonC;
Button buttonD;
Button fxA;
Button fxB;
RotaryEncoder knobLeft;
RotaryEncoder knobRight;

// 기판을 활성화하여 신호를 받을 수 있도록 합니다.
void setup()
{
	gameController.init();

	buttonStart.init(BUTTON_START_INPUT, BUTTON_START_OUTPUT, BUTTON_START_DEBOUNCING_PERIOD);
	buttonA.init(BUTTON_A_INPUT, BUTTON_A_OUTPUT, BUTTON_ALL_DEBOUNCING_PERIOD);
	buttonB.init(BUTTON_B_INPUT, BUTTON_B_OUTPUT, BUTTON_ALL_DEBOUNCING_PERIOD);
	buttonC.init(BUTTON_C_INPUT, BUTTON_C_OUTPUT, BUTTON_ALL_DEBOUNCING_PERIOD);
	buttonD.init(BUTTON_D_INPUT, BUTTON_D_OUTPUT, BUTTON_ALL_DEBOUNCING_PERIOD);
	fxA.init(FX_A_INPUT, FX_A_OUTPUT, BUTTON_ALL_DEBOUNCING_PERIOD);
	fxB.init(FX_B_INPUT, FX_B_OUTPUT, BUTTON_ALL_DEBOUNCING_PERIOD);

	knobRight.init(KNOB_RIGHT_INPUT_LEFT, KNOB_RIGHT_OUTPUT_LEFT, KNOB_RIGHT_INPUT_RIGHT, KNOB_RIGHT_OUTPUT_RIGHT, KNOB_ALL_DEBOUNCING_PERIOD);
	knobLeft.init(KNOB_LEFT_INPUT_LEFT, KNOB_LEFT_OUTPUT_LEFT, KNOB_LEFT_INPUT_RIGHT, KNOB_LEFT_OUTPUT_RIGHT, KNOB_ALL_DEBOUNCING_PERIOD);
}
